version: "3.8"
services:
  app:
    image: vmms-frontend
    build:
      context: ./
      dockerfile: docker/prod.Dockerfile
    volumes: # persist data
      - .:/vmms-frontend
      - /vmms-frontend/node_modules
      - /vmms-frontend/.next
    ports:
      - "3001:3000"
