import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers";
import { Theme } from "@radix-ui/themes";
import SideBar from "./components/side-bar";
import NavBar from "./components/nav-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        {/* <NextAuthProvider>{children}</NextAuthProvider> */}
        <Theme>
          <div className="bg-[#D9D9D9] min-h-[100vh]">
            <NavBar />
            <SideBar />
            {children}
          </div>
        </Theme>
      </body>
    </html>
  );
}
