import "./globals.css";
// import { Inter } from "next/font/google";
import Provider from "./providers";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { Theme } from "@radix-ui/themes";
import { redirect } from "next/navigation";
import SideBar from "./components/side-bar";
import NavBar from "./components/nav-bar";
// import { getServerSession } from "next-auth";
import { getServerSession } from "next-auth";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  if (!session) redirect("/login");

  return (
    <html lang="en">
      <body className="">
        <Provider>
          <Theme>
            <div className="bg-[#D9D9D9] min-h-[100vh]">
              <NavBar />
              <SideBar />
              {children}
            </div>
          </Theme>
        </Provider>
      </body>
    </html>
  );
}
